apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simeplepython.fullname" . }}
  labels:
    app: {{ include "simeplepython.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simeplepython.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simeplepython.name" . }}
    spec:
      containers:
      - name: {{ include "simeplepython.name" . }}
        image: {{ .Values.image.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
        command: ["python3"]
        args: ["-m http.server {{ .Values.service.port }}"]
