kind: Service
apiVersion: v1
metadata:
  name: {{ include "jukpython.name" . }}
  labels:
    app: {{ include "jukpython.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.exposePort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "jukpython.name" . }}
