apiVersion: v1
kind: Service
metadata:
  name: {{ include "jpython.fullname" . }}-headless
  labels:
{{ include "jpython.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jpython.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
