apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jpython
  namespace: japp
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jpython
  targetCPUUtilizationPercentage: 50
