{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jpython.serviceAccountName" . }}
  labels:
{{ include "jpython.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
{{- end -}}
