{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jnginx.serviceAccountName" . }}
  labels:
{{ include "jnginx.labels" . | indent 4 }}
{{- end -}}
