{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dnginx.serviceAccountName" . }}
  labels:
{{ include "dnginx.labels" . | indent 4 }}
  namespace: japp
{{- end -}}
